/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import GtitConstructionDeskImage from 'src/assets/images/Desktop1921_GTIT_Construction_Desktop.png';
import { styled } from '@mui/material/styles';

const Desktop19211 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const GtitConstructionDesk = styled('img')({
  height: `768.17px`,
  width: `1348px`,
  position: `absolute`,
  left: `286px`,
  top: `122px`,
});

function Desktop1921(props) {
  return (
    <Desktop19211 className={props.className}>
      <GtitConstructionDesk
        src={GtitConstructionDeskImage}
        loading="lazy"
        alt={'GTIT_Construction_Desktop'}
      />
    </Desktop19211>
  );
}

export default Desktop1921;
